spring:
  application:
    name: online-store-spring-boot

  datasource:
    url: jdbc:postgresql://localhost:5432/market
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
    locations: classpath:db/migration

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,logfile,threaddump
  info:
    build:
      enabled: true
    java:
      enabled: true
    process:
      enabled: true

jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 30m
  refresh:
    lifetime: 10d

application:
  name: Online store by spring boot
  version: 1.0.0




